### ISSUE TITLE
Allow filtering of available drives based on tags

### ISSUE THREAD

**Issue by lukegothic** [chilli-axe/mpc-autofill#112]
With the growing list of available drives, it is becoming more of a hassle to choose the correct version of a card in the app, and especially if you are looking up to something specific, in that case I sometimes find it faster to create the card myself.

I am going to elaborate on a solution to this problem that would affect multiple parts of the app:

First, we need to **come up with a set of characteristics that the available renders have,** this list must be throughout so we should have a brainstorm to cover most of the characteristics and cases, some examples here:
- Template: Classic, Normal...
- Art style: Normal, Extended, Full art...
- Art source: Original, Custom...
- Other minor things like set symbol Y/N...

Second, althought we could fill this information ourselves, it is better to **provide an endpoint that allows a contributor to fill this information about his drive** so it ends up inside mpcfill drive database. I do not know if there is a frontend already available to manage contributor drives, if it isn't, this would be a new admin/manager frontend on the mpcfill stack. Either way we need a way to tag drives.

Third, **add a parameter/tag selector inside the landing page of mpcfill so a user is able to filter drives** based on render criteria and the available tags.

Expected problems: Drivers that have multiple kind of renders available, so its owner is forced to choose multiple characteristics, ending up on that drive showing up on multiple parameter combinations. I'd be wise to invite contributors to arrange their drives/folders to match a specific set of characteristics and then allow them to list those drivers or folders separately and tag them more accurate.

**Comment by glandu-sr** [comment]
Could be integrated, at least the first point to #89

**Comment by ndepaola** [comment]
thanks for the detailed suggestions, these are good ideas :) the implementation of tags needs more thought - the current line of thinking is that tags will be per-image rather than per-source though. creating an admin interface for contributors to specify tags through the site is an interesting idea

**Comment by Bradw-17** [comment]
Just going to throw in my 2 cents as a creator and user of MPCfill:

Instead of trying to create tags with attributes of each individual image (Extended, full art, etc.) I feel like it would be quicker and more effective to have a search function based on creator user names or the whatever pre-existing descriptions the creators have added in parentheses.

For example: I know the Trix_Are_For_Scoot alts are very popular. But it can be a hassle trying to search through however many cards for the right one. With this functionality, a user could simply type "Trix_Are_For_Scoot" in a search bar at the top of the version selector, and filter through so you can see all of the alts that creator has made.

Also, I don't know if this is common practice, but to me it make sense to put the artists name or a description of a particular alt into the parenthesis following the card name. With the search function, you could look up all the alts of a particular card with a particular artists design. I have whole collections of cards by certain artists (we'll use Alex Pardee as an example). So if I wanted to see if any alts exist with arts from that artist, I could simply search "Alex Pardee" and filter through all the alts to see if there is one with his art on it.

 Another good use case would be for searching for lands in particular. We are getting close to 1000 different designs for basic lands, and trying to find any in particular can take a LOT of time. Filtering to one creators alts would save a huge amount of this time.

**Comment by davidianstyle** [comment]
@Bradw-17 I think the functionality for filtering by creator that you're looking for already exists.

All you have to do is:
1. Click 'Settings'
![MPC Fill - Google Chrome 12_8_2022 10_12_36 PM (2)](https://user-images.githubusercontent.com/6446624/206616075-e78a95ca-f659-4d95-a877-5a649b707333.jpg)
2. Drag the creator(s) you prefer to the top and turn off creator(s) you don't want to see
![MPC Fill - Google Chrome 12_8_2022 10_14_23 PM (2)](https://user-images.githubusercontent.com/6446624/206616289-37efe131-af42-498c-8591-03e8815eb1aa.jpg)
3. Voila! Your search will be filtered and sorted by creator(s) you've chosen and prioritized.

**Comment by Bradw-17** [comment]
@davidianstyle I didn't realize this was available, thanks! That does help a fair bit, but I wouldn't want to exclude any artists as a whole. And that still leaves tons of options at once, even though they are sorted by preference.

I'm just picturing an easy to use GUI search bar at the top of the version selector where you can enter a creator name, artist name, etc. and see if you get any results. If not, you can search for a different artist or clear the search bar and look through all the options as we currently do.

Say a person goes on, isn't sure what style of card they are after, but stumbles upon one they end up liking. Instead of then having to continually scroll searching for that one creators card style on another card, they could do a quick search, see if that creator has done the same style of alts to other cards, and if not, they could choose to continue scrolling and find another style.

Just an idea, and of course I don't have the skill to code the functionality or I would create a PR myself. But I feel it would be pretty useful and intuitive for new (and old) users, as well as being easier to code a simple text search option rather than having to create tags which would need to be individually applied to every single card in the database.
