### ISSUE TITLE
desktop windows app has tuple out of range exception

### ISSUE THREAD

**Issue by DusilB** [chilli-axe/mpc-autofill#180]
# System

- win 11 home:
- 4.3.2:
- Chrome:  117.0.5938.63

# Affected Components

- [ ] Backend
- [ ] Frontend
- [x] Desktop Tool

# Description

Have a set of 540 cards that I'm trying to print. I run the program and it hangs after uploading card fronts. Says there is a tuple index out of range

<img width="869" alt="image" src="https://github.com/chilli-axe/mpc-autofill/assets/31486894/cb3880cd-aab7-4512-9e53-d102afd91cc1">

-

# Steps to Reproduce

Problem is consistent. I open the program. Select y, chrome, [enter].
I sign into my account, and nav to the project that it failed on the first time.
I go back to the terminal, hit [enter] and it spins, then says there's a tuple index out of range error.

Previous version does not work either.

-

**Comment by benplum** [comment]
Same issue, same version, but on MacOS.

**Comment by jdstamp** [comment]
I am having the same issue on MacOS

**Comment by ndepaola** [comment]
sorry about this issue folks! this issue is fixed in `master` but i haven't created a release containing the fix yet for two reasons:

* brave support is broken in the most recent release (tracked here: #168) because of a bug in the webdriver management library we depend on (tracked here: https://github.com/SergeyPirogov/webdriver_manager/issues/613). i haven't spent any time looking into whether i can put a PR into `webdriver_manager` myself to fix this yet since the library maintainer doesn't care about brave support. i don't want to have two releases in a row with broken brave support
* this PR #181 was merged in a few weeks ago, but i want to extend that solution to enable full support for printerstudio.com in time for the next release - just haven't gotten around to sitting down and working on that yet

**Comment by ndepaola** [comment]
a quick update on this:

1. addressed by #192 by yeeting off `webdriver_manager`
2. addressed by #191

so i'll put together a new release once my manual testing for the first of those PRs is all squared away :)

**Comment by ndepaola** [comment]
addressed in the latest release https://github.com/chilli-axe/mpc-autofill/releases/tag/v4.4 :)
