### ISSUE TITLE
M2 mac: bad CPU type in executable: /Users/name/Desktop/autofill-macos

### ISSUE THREAD

**Issue by warronbebster** [chilli-axe/mpc-autofill#247]
# System

- **MacOS 14.2.1, M2 2023**:
- **Desktop Tool Version**: 4.5.1
- **Browser (including version)**:Chrome

# Affected Components

- [ ] Backend
- [ ] Frontend
- [x] Desktop Tool

# Description

Running the tool on M2 Macbook pro results in an error:
<img width="682" alt="image" src="https://github.com/chilli-axe/mpc-autofill/assets/8211247/95bf5c0f-beb8-46c3-adf2-f0d6c03925b9">

-

# Steps to Reproduce

attempt to run the tool on macOS 14 with M2 Macbook Pro
-

**Comment by ndepaola** [comment]
thanks for letting me know about this - i'll look into how i need to reconfigure the build to support M2 macs. unfortunately i don't have one handy to test with.

in the meantime, you can work around this issue by running the source code directly rather than running the pre-built binary - instructions for this are in the wiki

**Comment by warronbebster** [comment]
For posterity, if you install [rosetta](https://support.apple.com/en-us/102527) it will work!

**Comment by ndepaola** [comment]
it looks like github actions supports x86 and ARM macOS runners: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-private-repositories

i'll update the build process to target both - there will be two macOS binaries in each release beginning from the next one 🚀
