### ISSUE TITLE
Seeing 404 errors

### ISSUE THREAD

**Issue by FearsFall** [chilli-axe/mpc-autofill#262]
# System
Widows PC running windows 11

- **Windows 11**:
- **Desktop Tool Version**:
- **Chrome**:

# Affected Components

- [ ] Backend
- [x] Frontend
- [ ] Desktop Tool

# Description

-

# Steps to Reproduce

-

**Comment by FearsFall** [comment]
Seeing 404 errors on MPCFill website

**Comment by ndepaola** [comment]
howdy - this issue is light on detail so the support i can give you is limited.

our image serving system caches a thumbnail once *any* user tries to load it for the first time, then serves the cached thumbnail from then onwards. we have this system because google is extremely aggressive with rate limiting users when they try to load thumbnails from google drive (where our thumbnails are sourced from before they're cached).

so it's likely this issue would be resolved for the images which 404'd by refreshing the page.
